name: CI Smart Access Edge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore backend
        run: dotnet restore backend/SmartAccess/SmartAccess.API/SmartAccess.API.csproj

      - name: Build backend
        run: dotnet build backend/SmartAccess/SmartAccess.API/SmartAccess.API.csproj --configuration Release --no-restore

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install frontend
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build